"C:\Program Files\Java\jdk-11\bin\javac.exe" .\View\AbstractDrawable.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Model\Ball.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\View\DrawableBall.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\View\DrawableLine.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\View\DrawableObjectFactory.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\View\DrawablePolyLine.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Model\Enum_Object_Model.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\View\FrmMain.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Model\Game.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Model\Line.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" MainClass.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Model\ObjectModel.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Model\Observer.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Model\Outline.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Control.\Outline_Collision.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\View\PnlGame.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\View\pnlSpeed.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Model\Point.java
"C:\Program Files\Java\jdk-11\bin\javac.exe" .\Control.\Processor.java

